In [1]:
import numpy as np

In [2]:
#This load a sample dataset to see how our algorithm performs
def loadDataSet():      
    dataMat = []                
    fr = open('testSet.txt')
    for line in fr.readlines():
        curLine = line.strip().split('\t')
        fltLine = list(map(float,curLine))
        dataMat.append(fltLine)
    return dataMat

In [3]:
#This calculate the euclidean distance of two vector
def eucli_dist(v1,v2):
    return np.sqrt(np.sum(np.power(v1-v2,2)))

In [4]:
#Generate k random centroids within the dataset
def rand_centroids(df,num_centroids):
    n = np.shape(df)[1]
    centroids = np.mat(np.zeros((num_centroids,n)))
    for i in range(n):
        minJ = min(df[:,i])
        rangeJ = float(max(df[:,i]) - minJ)
        centroids[:,i] = minJ + rangeJ * np.random.rand(num_centroids,1)
    return centroids

In [23]:
def KMeans(df, num_centroids, distMsr=eucli_dist):
    m = np.shape(df)[0]
    clusterAssment = np.mat(np.zeros((m,2)))
    centroids = rand_centroids(df,num_centroids)
    changed = True
    while changed:
        changed = False
        for i in range(m):
            minDist = np.inf
            minIndex = -1
            for j in range(num_centroids):
                distJI = distMsr(centroids[j,:],df[i,:])
                if distJI < minDist:
                    minDist = distJI; minIndex = j
            if clusterAssment[i,0] != minIndex: changed = True
            clusterAssment[i,:] = minIndex, minDist**2
        print(centroids)
        for cent in range(num_centroids):
            ptsInClust = df[np.nonzero(clusterAssment[:,0].A==cent)[0]]
            centroids[cent,:] = np.mean(ptsInClust,axis=0)
    return centroids, clusterAssment

In [40]:
data = np.mat(loadDataSet())

In [41]:
rand_centroids(data,4)

matrix([[ 2.66269273, -3.11987452],
        [ 1.70423694,  4.04981917],
        [-3.08444497,  4.4155119 ],
        [ 1.7914739 ,  0.65450303]])

In [42]:
myCentroids, clustAssing = KMeans(data,4)

[[ 2.06349499  4.82637691]
 [-3.53086452 -0.13280405]
 [ 2.05429364  3.5187194 ]
 [ 4.69661925  1.69265285]]
[[ 1.4008295   4.71308625]
 [-2.90909524 -0.62810416]
 [ 1.64181288  2.80707553]
 [ 3.27344881 -1.82669405]]
[[ 1.12304829  4.313196  ]
 [-3.17988762 -0.66398703]
 [ 1.88985089  2.70303026]
 [ 2.80293085 -2.7315146 ]]
[[-0.05483858  3.75554275]
 [-3.34884281 -0.77772481]
 [ 2.53230537  2.6238155 ]
 [ 2.65077367 -2.79019029]]
[[-1.60460037  3.19429405]
 [-3.54251791 -2.066412  ]
 [ 2.82411853  2.92788124]
 [ 2.65077367 -2.79019029]]
[[-2.46154315  2.78737555]
 [-3.53973889 -2.89384326]
 [ 2.6265299   3.10868015]
 [ 2.65077367 -2.79019029]]
